// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umfg.Repositorio.Classes;

#nullable disable

namespace Umfg.Repositorio.Migrations
{
    [DbContext(typeof(MySqlDataBaseContext))]
    partial class MySqlDataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Umfg.Dominio.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NR_CELULAR")
                        .HasAnnotation("Relational:JsonPropertyName", "celular");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NR_DOCUMENTO")
                        .HasAnnotation("Relational:JsonPropertyName", "documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_EMAIL")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_ENDERECO")
                        .HasAnnotation("Relational:JsonPropertyName", "endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NM_CLIENTE")
                        .HasAnnotation("Relational:JsonPropertyName", "nome");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_OBSERVACAO")
                        .HasAnnotation("Relational:JsonPropertyName", "observacao");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Umfg.Dominio.Entidades.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("CD_BARRA")
                        .HasAnnotation("Relational:JsonPropertyName", "codigoBarra");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DS_PRODUTO")
                        .HasAnnotation("Relational:JsonPropertyName", "descricao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VL_PRODUTO")
                        .HasAnnotation("Relational:JsonPropertyName", "valor");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
